name: Feature Request
description: Propose an enhancement
title: "[Feature]: "
labels: ["feature", "priority:p2"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What user problem are we solving?
      placeholder: Describe the pain point.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the desired behavior and scope
      placeholder: Describe the proposed feature.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List measurable criteria
      placeholder: |
        - [ ] ...
        - [ ] ...
